# Generated by Django 3.2.13 on 2022-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
